jenkins:
  url: 'http://172.168.1.10:8088/'
  username: admin
  password: 123456
gitlab:
  url: http://172.168.1.10/
  token: glpat-57WwyFMeYAsszMzyzjsn
db:
  driver: mysql
  database: jenkins
  username: root
  password: Unipal666
  host: 172.168.1.10
  port: 3306
  max_idle_conns: 2
  max_open_conns: 5
  conn_max_lifetime: 3600
  